require('plugins')
require('options')
require('keymaps')

require('plug-treesitter')
require('plug-lualine')
require('plug-lspconfig')
require('plug-cmp')
require('plug-comment')
require('plug-telescope')
require('plug-mason')
require('plug-workspaces')
require('plug-sessions')
require('plug-pretty-fold')
